In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import pandas as pd

In [4]:
df = pd.read_csv("../Data/processed/Crop_recommendation_processed.csv")

In [5]:
X = df.drop("label",axis=1)
y = df["label"]

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
models = {

    "Logistic Regression": LogisticRegression(max_iter=5000),

    "KNN": KNeighborsClassifier(),

    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(random_state=42)

}

In [16]:
results = []

for name, model in models.items():


    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(
        y_test,
        y_pred,
        average="weighted"
    )

    recall = recall_score(
        y_test,
        y_pred,
        average="weighted"
    )

    f1 = f1_score(
        y_test,
        y_pred,
        average="weighted"
    )

    results.append({
    "Model": name,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "Model Object": model
})

c:\PROJECT\Smart_Agricultural_project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 5000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=5000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
results_df = pd.DataFrame(results)

results_df

,Model,Accuracy,Precision,Recall,F1 Score,Model Object
0,Logistic Regression,0.972727,0.973501,0.972727,0.972628,LogisticRegression(max_iter=5000)
1,KNN,0.970455,0.973976,0.970455,0.970311,KNeighborsClassifier()
2,Decision Tree,0.986364,0.986806,0.986364,0.986315,DecisionTreeClassifier(random_state=42)
3,Random Forest,0.993182,0.993735,0.993182,0.993175,"(DecisionTreeClassifier(max_features='sqrt', r..."

In [19]:
results_df = results_df.sort_values(
    by="Accuracy",
    ascending=False
)

results_df

,Model,Accuracy,Precision,Recall,F1 Score,Model Object
3,Random Forest,0.993182,0.993735,0.993182,0.993175,"(DecisionTreeClassifier(max_features='sqrt', r..."
2,Decision Tree,0.986364,0.986806,0.986364,0.986315,DecisionTreeClassifier(random_state=42)
0,Logistic Regression,0.972727,0.973501,0.972727,0.972628,LogisticRegression(max_iter=5000)
1,KNN,0.970455,0.973976,0.970455,0.970311,KNeighborsClassifier()

In [20]:
best_model = results_df.iloc[0]

print(best_model)

Model                                               Random Forest
Accuracy                                                 0.993182
Precision                                                0.993735
Recall                                                   0.993182
F1 Score                                                 0.993175
Model Object    (DecisionTreeClassifier(max_features='sqrt', r...
Name: 3, dtype: object